# Generated by Django 5.1.2 on 2025-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisor',
            name='v_habilitarMun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisor',
            name='v_registrarMun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisor',
            name='v_revSolicitud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisor',
            name='vl_convocatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisor',
            name='vl_revisores',
            field=models.BooleanField(default=False),
        ),
    ]
