# Generated by Django 5.1.2 on 2025-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_revisor_v_habilitarmun_revisor_v_registrarmun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='v_habilitarMun',
        ),
        migrations.RemoveField(
            model_name='revisor',
            name='v_registrarMun',
        ),
        migrations.RemoveField(
            model_name='revisor',
            name='v_revSolicitud',
        ),
        migrations.RemoveField(
            model_name='revisor',
            name='vl_convocatoria',
        ),
        migrations.RemoveField(
            model_name='revisor',
            name='vl_revisores',
        ),
        migrations.AddField(
            model_name='user',
            name='v_habilitarMun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='v_registrarMun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='v_revSolicitud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vl_convocatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vl_revisores',
            field=models.BooleanField(default=False),
        ),
    ]
