# Generated by Django 5.1.2 on 2025-05-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0002_initial'),
        ('solicitud', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='datos_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulacion', to='proyecto.datosproyectobase', to_field='slug'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_mae_p', to='user.encargadomae'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Datos_base_proyecto', to='solicitud.municipios'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_p', to='user.responsablep'),
        ),
    ]
