# Generated by Django 5.1.2 on 2025-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('TARIJA', 'TARIJA'), ('CHUQUISACA', 'CHUQUISACA'), ('COCHABAMBA', 'COCHABAMBA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('EN PROCESO', 'EN PROCESO'), ('APROBADO', 'APROBADO'), ('FINALIZADO', 'FINALIZADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
