# Generated by Django 5.1.2 on 2025-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI'), ('COCHABAMBA', 'COCHABAMBA'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO'), ('EN PROCESO', 'EN PROCESO'), ('NINGUNO', 'NINGUNO'), ('FINALIZADO', 'FINALIZADO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
