# Generated by Django 5.1.2 on 2025-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('BENI', 'BENI'), ('POTOSI', 'POTOSI'), ('LA PAZ', 'LA PAZ'), ('COCHABAMBA', 'COCHABAMBA'), ('ORURO', 'ORURO'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('FINALIZADO', 'FINALIZADO'), ('EN PROCESO', 'EN PROCESO'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
