# Generated by Django 5.1.2 on 2025-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('COCHABAMBA', 'COCHABAMBA'), ('LA PAZ', 'LA PAZ'), ('PANDO', 'PANDO'), ('POTOSI', 'POTOSI'), ('BENI', 'BENI'), ('ORURO', 'ORURO'), ('CHUQUISACA', 'CHUQUISACA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EN EJECUCION', 'EN EJECUCION'), ('SOLICITUD', 'SOLICITUD'), ('FINALIZADO', 'FINALIZADO')], max_length=255),
        ),
    ]
