# Generated by Django 5.1.2 on 2025-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA'), ('COCHABAMBA', 'COCHABAMBA'), ('POTOSI', 'POTOSI'), ('TARIJA', 'TARIJA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('LA PAZ', 'LA PAZ'), ('ORURO', 'ORURO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('EN EJECUCION', 'EN EJECUCION'), ('FINALIZADO', 'FINALIZADO')], max_length=255),
        ),
    ]
