# Generated by Django 5.1.2 on 2025-02-09 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproyectobase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edtp',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPproyectoBeneficiario', to='proyecto.beneficiario'),
        ),
        migrations.AddField(
            model_name='edtp',
            name='datos_basicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPDatosBase', to='proyecto.datosproyectobase'),
        ),
        migrations.AddField(
            model_name='edtp',
            name='declaracionJurada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPDeclaracionJ', to='proyecto.declaracion_jurada'),
        ),
        migrations.AddField(
            model_name='edtp',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edtp',
            name='objetivo_gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPObjGeneral', to='proyecto.objetivogeneralejec'),
        ),
        migrations.AddField(
            model_name='edtp',
            name='presupuestoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPPreupuestoRef', to='proyecto.presupuestoreferencial'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoBeneficiario', to='proyecto.beneficiario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='conclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoConclusionR', to='proyecto.conclusion_recomendacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='datos_basicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDatosBase', to='proyecto.datosproyectobase'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='declaracionJurada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDeclaracionJ', to='proyecto.declaracion_jurada'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='detallePoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDetallePoa', to='proyecto.detalle_poa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ideaProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoIdea', to='proyecto.idea_proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impactoAmbiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoImpactoAmbiental', to='proyecto.impacto_ambiental'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoJustificacion', to='proyecto.justificacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuestoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoPreupuestoRef', to='proyecto.presupuestoreferencial'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edtp',
            name='Ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPubicacion', to='proyecto.ubicaciongeografica'),
        ),
    ]
