# Generated by Django 5.1.2 on 2024-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproyectobase',
            name='periodo_ejecu',
            field=models.IntegerField(choices=[('1', '1'), ('3', '3'), ('2', '2')]),
        ),
    ]
