# Generated by Django 5.1.2 on 2024-11-15 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatoria', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('solicitud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproyectobase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_beneficiario', to='proyecto.beneficiario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='conclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_conclusionR', to='proyecto.conclusion_recomendacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_convocatoria', to='convocatoria.convocatoria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='datos_basicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_DatosBase', to='proyecto.datosproyectobase'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='declaracionJurada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_DeclaracionJ', to='proyecto.declaracion_jurada'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='detallePoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_DetallePoa', to='proyecto.detalle_poa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ideaProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_idea', to='proyecto.idea_proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impactoAmbiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_impactoAmbiental', to='proyecto.impacto_ambiental'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_justificacion', to='proyecto.justificacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_postulacion', to='solicitud.postulacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuestoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_preupuestoRef', to='proyecto.presupuestoreferencial'),
        ),
    ]
