# Generated by Django 5.1.2 on 2024-10-30 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproyectobase',
            name='solicitud_financ',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datosproyectobase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_proyecto', to=settings.AUTH_USER_MODEL),
        ),
    ]
