# Generated by Django 5.1.2 on 2024-10-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_datosproyectobase_periodo_ejecu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproyectobase',
            name='periodo_ejecu',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')]),
        ),
    ]
