# Generated by Django 5.1.2 on 2024-11-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='convocatoria',
        ),
    ]
