# Generated by Django 5.1.2 on 2024-11-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_proyecto_convocatoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion_jurada',
            old_name='consultoria',
            new_name='financiamiento',
        ),
    ]
