# Generated by Django 5.1.2 on 2024-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_datosproyectobase_solicitud_financ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('justificacion1', models.BooleanField()),
                ('justificacion2', models.BooleanField()),
                ('justificacion3', models.BooleanField()),
                ('justificacion4', models.BooleanField()),
                ('justificacion5', models.BooleanField()),
                ('justificacion6', models.BooleanField()),
                ('justificacion7', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Justificacion',
                'verbose_name_plural': 'Justificaciones',
                'db_table': 'Justificacion',
            },
        ),
        migrations.AlterField(
            model_name='datosproyectobase',
            name='periodo_ejecu',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
