# Generated by Django 5.1.2 on 2024-11-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_rename_consultoria_declaracion_jurada_financiamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracion_jurada',
            name='financiamiento',
        ),
    ]
