# Generated by Django 5.1.2 on 2024-11-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_declaracion_jurada_financiamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='postulacion',
        ),
    ]
