# Generated by Django 5.1.2 on 2024-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_beneficiario_conclusion_recomendacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_acta',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='objetivo_especifico',
            name='slug',
            field=models.SlugField(),
        ),
    ]
