# Generated by Django 5.1.2 on 2024-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_modelo_acta_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo_desastre',
            name='slug',
            field=models.SlugField(),
        ),
    ]
