# Generated by Django 5.1.2 on 2024-11-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_remove_proyecto_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='aceptar',
            field=models.CharField(default='SIN REVISAR', max_length=50, verbose_name=[('SIN REVISAR', 'SIN REVISAR'), ('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO')]),
        ),
    ]
