# Generated by Django 5.1.2 on 2024-11-04 07:49

import proyecto.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_riesgo_desastre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion_jurada',
            name='carta',
            field=models.FileField(upload_to=proyecto.upload.docDeclaracionjurada),
        ),
        migrations.AlterField(
            model_name='declaracion_jurada',
            name='consultoria',
            field=models.FileField(upload_to=proyecto.upload.docDeclaracionjurada),
        ),
        migrations.AlterField(
            model_name='declaracion_jurada',
            name='declaracion',
            field=models.FileField(upload_to=proyecto.upload.docDeclaracionjurada),
        ),
        migrations.AlterField(
            model_name='declaracion_jurada',
            name='itcp',
            field=models.FileField(upload_to=proyecto.upload.docDeclaracionjurada),
        ),
        migrations.AlterField(
            model_name='derecho_propietario',
            name='si_registro',
            field=models.FileField(blank=True, null=True, upload_to=proyecto.upload.docDerechoPropietario),
        ),
        migrations.AlterField(
            model_name='modelo_acta',
            name='no_acta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_acta',
            name='si_acta',
            field=models.FileField(blank=True, null=True, upload_to=proyecto.upload.docModeloActa),
        ),
    ]
