# Generated by Django 5.1.2 on 2024-12-02 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoBeneficiario', to='proyecto.beneficiario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='conclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoConclusionR', to='proyecto.conclusion_recomendacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='datos_basicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDatosBase', to='proyecto.datosproyectobase'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='declaracionJurada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDeclaracionJ', to='proyecto.declaracion_jurada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='detallePoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDetallePoa', to='proyecto.detalle_poa'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ideaProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoIdea', to='proyecto.idea_proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='impactoAmbiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoImpactoAmbiental', to='proyecto.impacto_ambiental'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoJustificacion', to='proyecto.justificacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuestoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoPreupuestoRef', to='proyecto.presupuestoreferencial'),
        ),
    ]
