# Generated by Django 5.1.2 on 2025-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_proyecto_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproyectobase',
            name='solicitud_financ',
            field=models.BooleanField(default=False),
        ),
    ]
