# Generated by Django 5.1.2 on 2025-01-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_alter_datosproyectobase_solicitud_financ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosproyectobase',
            name='solicitud_financ',
        ),
    ]
