# Generated by Django 5.1.2 on 2025-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_remove_datosproyectobase_solicitud_financ'),
    ]

    operations = [
        migrations.AddField(
            model_name='impacto_ambiental',
            name='otros',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
