# Generated by Django 5.1.2 on 2025-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_impacto_ambiental_otros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impacto_ambiental',
            old_name='otros',
            new_name='otro_nombre',
        ),
        migrations.AddField(
            model_name='impacto_ambiental',
            name='otro_nivel',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impacto_ambiental',
            name='otro_tempo',
            field=models.CharField(blank=True, choices=[('Transitorio', 'Transitorio'), ('Permanente', 'Permanente')], max_length=255, null=True),
        ),
    ]
