# Generated by Django 5.1.2 on 2025-01-30 13:04

import proyecto.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_rename_otros_impacto_ambiental_otro_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracion_jurada',
            name='carta',
        ),
        migrations.AddField(
            model_name='declaracion_jurada',
            name='carta_ejec',
            field=models.FileField(blank=True, null=True, upload_to=proyecto.upload.docDeclaracionjurada),
        ),
        migrations.AddField(
            model_name='declaracion_jurada',
            name='carta_elab',
            field=models.FileField(blank=True, null=True, upload_to=proyecto.upload.docDeclaracionjurada),
        ),
    ]
