# Generated by Django 5.1.2 on 2025-02-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_datosproyectobase_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosproyectobase',
            name='creador',
        ),
    ]
