# Generated by Django 5.1.2 on 2025-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_remove_datosproyectobase_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEspecificoEjec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('fechaenvio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('nro', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('componente', models.TextField()),
                ('meta', models.TextField()),
            ],
            options={
                'verbose_name': 'ObjetivoEspecificoEjec',
                'verbose_name_plural': 'ObjetivosEspecificoEjec',
                'db_table': 'ObjetivoEspecificoEjec',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoGeneralEjec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaenvio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('objetivo_general', models.TextField()),
                ('hectareas', models.IntegerField()),
                ('tipo_hectareas', models.CharField(choices=[('Forestacion', 'Forestacion'), ('Reforestacion', 'Reforestacion'), ('Manejo sustentable de bosque', 'Manejo sustentable de bosque'), ('Forestacion y Reforestacion', 'Forestacion y Reforestacion'), ('Forestacion y Manejo sustentable de bosque', 'Forestacion y Manejo sustentable de bosque'), ('Reforestacion y Manejo sustentable de bosque', 'Reforestacion y Manejo sustentable de bosque'), ('Forestacion, Reforestacion y Manejo sustentable de bosque', 'Forestacion, Reforestacion y Manejo sustentable de bosque')])),
            ],
            options={
                'verbose_name': 'ObjetivoGeneralEjec',
                'verbose_name_plural': 'ObjetivosGeneralesEjec',
                'db_table': 'ObjetivoGeneralEjec',
            },
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'ProyectoITCP', 'verbose_name_plural': 'ProyectosITCP'},
        ),
        migrations.AlterField(
            model_name='datosproyectobase',
            name='periodo_ejecu',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36)]),
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='ProyectoITCP',
        ),
    ]
