# Generated by Django 5.1.2 on 2025-02-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_remove_objetivoespecificoejec_nro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaenvio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('alturaForestacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UbicacionGeografica',
                'verbose_name_plural': 'UbicacionesGeografica',
                'db_table': 'UbicacionGeografica',
            },
        ),
    ]
