# Generated by Django 5.1.2 on 2025-02-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0022_ubicaciongeografica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EDTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaenvio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('aceptar', models.BooleanField()),
                ('estado', models.CharField(choices=[('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO')], default='SIN REVISAR', max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPubicacion', to='proyecto.ubicaciongeografica')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPproyectoBeneficiario', to='proyecto.beneficiario')),
                ('datos_basicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPDatosBase', to='proyecto.datosproyectobase')),
                ('declaracionJurada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPDeclaracionJ', to='proyecto.declaracion_jurada')),
                ('objetivo_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPObjGeneral', to='proyecto.objetivogeneralejec')),
                ('presupuestoRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDTPPreupuestoRef', to='proyecto.presupuestoreferencial')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EDTP',
                'verbose_name_plural': 'EDTP',
                'db_table': 'EDTP',
            },
        ),
    ]
