# Generated by Django 5.1.2 on 2025-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0023_edtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='edtp',
            name='fechaEstado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
