departamentos = {
    ('LA PAZ', 'LA PAZ'),
    ('ORURO ', 'ORURO'),
    ('POTOSI', 'POTOSI'),
    ('CHUQUISACA', 'CHUQUISACA'),
    ('COCHABAMBA', 'COCHABAMBA'),
    ('TARIJA', 'TARIJA'),
    ('SANTA CRUZ', 'SANTA CRUZ'),
    ('BENI', 'BENI'),
    ('PANDO', 'PANDO'),
}

entidad_territorial_autonoma = {
    ('GOBIERNO AUTÓNOMO DEPARTAMENTAL ', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'),
    ('GOBIERNO AUTÓNOMO MUNICIPAL ', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'),
    ('GOBIERNO AUTÓNOMO REGIONAL ', 'GOBIERNOS AUTÓNOMOS REGIONAL'),
    ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO ', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'),
}

estado_proyecto = {
    ('NINGUNO', 'NINGUNO'),
    ('SOLICITUD', 'SOLICITUD'),
    ('APROBADO', 'APROBADO'),
}

periodo_ejecucion = {
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
}
