# Generated by Django 5.1.2 on 2025-02-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO'), ('SANTA CRUZ', 'SANTA CRUZ'), ('CHUQUISACA', 'CHUQUISACA'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('TARIJA', 'TARIJA'), ('COCHABAMBA', 'COCHABAMBA')], max_length=30)),
                ('entidad_territorial', models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255)),
                ('p_a', models.BooleanField(default=False, verbose_name='Postulo Anteriormente')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimaconexion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('modificacion', models.BooleanField()),
                ('tipo_financiamiento', models.IntegerField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulacionConvocatoria', to='convocatoria.convocatoria')),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'Postulaciones',
            },
        ),
    ]
