# Generated by Django 5.1.2 on 2024-10-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('POTOSI', 'POTOSI'), ('LA PAZ', 'LA PAZ'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('CHUQUISACA', 'CHUQUISACA'), ('TARIJA', 'TARIJA'), ('ORURO ', 'ORURO'), ('PANDO', 'PANDO')], max_length=30)),
                ('entidad_territorial', models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD')], max_length=255)),
                ('p_a', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'Postulaciones',
            },
        ),
    ]
