# Generated by Django 5.1.2 on 2024-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('ORURO', 'ORURO'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('PANDO', 'PANDO'), ('POTOSI', 'POTOSI'), ('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('CHUQUISACA', 'CHUQUISACA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
