# Generated by Django 5.1.2 on 2024-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ'), ('SANTA CRUZ', 'SANTA CRUZ'), ('BENI', 'BENI'), ('POTOSI', 'POTOSI'), ('CHUQUISACA', 'CHUQUISACA'), ('COCHABAMBA', 'COCHABAMBA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
