# Generated by Django 5.1.2 on 2024-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='modificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('ORURO', 'ORURO'), ('CHUQUISACA', 'CHUQUISACA'), ('BENI', 'BENI'), ('POTOSI', 'POTOSI'), ('PANDO', 'PANDO'), ('LA PAZ', 'LA PAZ'), ('SANTA CRUZ', 'SANTA CRUZ'), ('TARIJA', 'TARIJA'), ('COCHABAMBA', 'COCHABAMBA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
