# Generated by Django 5.1.2 on 2024-11-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('CHUQUISACA', 'CHUQUISACA'), ('LA PAZ', 'LA PAZ'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
