# Generated by Django 5.1.2 on 2024-11-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_remove_proyecto_postulacion'),
        ('solicitud', '0006_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='datos_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulacion', to='proyecto.datosproyectobase', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('SANTA CRUZ', 'SANTA CRUZ'), ('CHUQUISACA', 'CHUQUISACA'), ('PANDO', 'PANDO'), ('COCHABAMBA', 'COCHABAMBA'), ('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('BENI', 'BENI'), ('LA PAZ', 'LA PAZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
