# Generated by Django 5.1.2 on 2024-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_postulacion_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('BENI', 'BENI'), ('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA'), ('COCHABAMBA', 'COCHABAMBA'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('SANTA CRUZ', 'SANTA CRUZ'), ('CHUQUISACA', 'CHUQUISACA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
