# Generated by Django 5.1.2 on 2024-11-25 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_remove_proyecto_postulacion'),
        ('solicitud', '0007_postulacion_datos_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('CHUQUISACA', 'CHUQUISACA'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('COCHABAMBA', 'COCHABAMBA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='datos_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulacion', to='proyecto.datosproyectobase', to_field='slug'),
        ),
    ]
