# Generated by Django 5.1.2 on 2024-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('TARIJA', 'TARIJA'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('CHUQUISACA', 'CHUQUISACA'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('SANTA CRUZ', 'SANTA CRUZ'), ('LA PAZ', 'LA PAZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('NINGUNO', 'NINGUNO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
