# Generated by Django 5.1.2 on 2024-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('CHUQUISACA', 'CHUQUISACA'), ('LA PAZ', 'LA PAZ'), ('SANTA CRUZ', 'SANTA CRUZ'), ('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('NINGUNO', 'NINGUNO'), ('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
