# Generated by Django 5.1.2 on 2024-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0009_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('COCHABAMBA', 'COCHABAMBA'), ('POTOSI', 'POTOSI'), ('BENI', 'BENI'), ('LA PAZ', 'LA PAZ'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('TARIJA', 'TARIJA'), ('ORURO', 'ORURO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
