# Generated by Django 5.1.2 on 2024-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0012_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('COCHABAMBA', 'COCHABAMBA'), ('TARIJA', 'TARIJA'), ('BENI', 'BENI'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO'), ('POTOSI', 'POTOSI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
