# Generated by Django 5.1.2 on 2024-12-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0014_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('POTOSI', 'POTOSI'), ('BENI', 'BENI'), ('LA PAZ', 'LA PAZ'), ('ORURO', 'ORURO'), ('CHUQUISACA', 'CHUQUISACA'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('COCHABAMBA', 'COCHABAMBA'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
