# Generated by Django 5.1.2 on 2025-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0015_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_ultimaconexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('SANTA CRUZ', 'SANTA CRUZ'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('CHUQUISACA', 'CHUQUISACA'), ('POTOSI', 'POTOSI'), ('COCHABAMBA', 'COCHABAMBA'), ('TARIJA', 'TARIJA'), ('PANDO', 'PANDO'), ('ORURO', 'ORURO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
