# Generated by Django 5.1.2 on 2025-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0016_postulacion_fecha_ultimaconexion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('POTOSI', 'POTOSI'), ('PANDO', 'PANDO'), ('COCHABAMBA', 'COCHABAMBA'), ('BENI', 'BENI'), ('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA'), ('ORURO', 'ORURO'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
