# Generated by Django 5.1.2 on 2025-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0017_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA'), ('POTOSI', 'POTOSI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('COCHABAMBA', 'COCHABAMBA'), ('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA'), ('BENI', 'BENI'), ('ORURO', 'ORURO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
