# Generated by Django 5.1.2 on 2025-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0018_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI'), ('TARIJA', 'TARIJA'), ('ORURO', 'ORURO'), ('COCHABAMBA', 'COCHABAMBA'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
