# Generated by Django 5.1.2 on 2025-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0019_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('ORURO', 'ORURO'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI'), ('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA'), ('LA PAZ', 'LA PAZ'), ('SANTA CRUZ', 'SANTA CRUZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
