# Generated by Django 5.1.2 on 2025-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0020_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='tipo_financiamiento',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('CHUQUISACA', 'CHUQUISACA'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('PANDO', 'PANDO'), ('ORURO', 'ORURO'), ('COCHABAMBA', 'COCHABAMBA'), ('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
