# Generated by Django 5.1.2 on 2025-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0021_postulacion_tipo_financiamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI'), ('PANDO', 'PANDO'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('CHUQUISACA', 'CHUQUISACA'), ('TARIJA', 'TARIJA'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
