# Generated by Django 5.1.2 on 2025-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0022_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('ORURO', 'ORURO'), ('TARIJA', 'TARIJA'), ('COCHABAMBA', 'COCHABAMBA'), ('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA'), ('POTOSI', 'POTOSI'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('LA PAZ', 'LA PAZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL')], max_length=100),
        ),
    ]
