# Generated by Django 5.1.2 on 2025-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0023_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('TARIJA', 'TARIJA'), ('COCHABAMBA', 'COCHABAMBA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI'), ('CHUQUISACA', 'CHUQUISACA'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ'), ('BENI', 'BENI'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
