# Generated by Django 5.1.2 on 2025-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0025_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('BENI', 'BENI'), ('ORURO', 'ORURO'), ('COCHABAMBA', 'COCHABAMBA'), ('PANDO', 'PANDO'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('POTOSI', 'POTOSI'), ('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
