# Generated by Django 5.1.2 on 2025-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0026_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('CHUQUISACA', 'CHUQUISACA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('TARIJA', 'TARIJA'), ('POTOSI', 'POTOSI'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('ORURO', 'ORURO'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('SOLICITUD', 'SOLICITUD'), ('RECHAZADO', 'RECHAZADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
