# Generated by Django 5.1.2 on 2025-01-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0028_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('PANDO', 'PANDO'), ('BENI', 'BENI'), ('SANTA CRUZ', 'SANTA CRUZ'), ('TARIJA', 'TARIJA'), ('CHUQUISACA', 'CHUQUISACA'), ('ORURO', 'ORURO'), ('COCHABAMBA', 'COCHABAMBA'), ('LA PAZ', 'LA PAZ'), ('POTOSI', 'POTOSI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('NINGUNO', 'NINGUNO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO', 'APROBADO')], max_length=255),
        ),
    ]
