# Generated by Django 5.1.2 on 2025-02-03 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0031_alter_municipios_departamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='creador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('BENI', 'BENI'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ'), ('SANTA CRUZ', 'SANTA CRUZ'), ('COCHABAMBA', 'COCHABAMBA'), ('CHUQUISACA', 'CHUQUISACA'), ('POTOSI', 'POTOSI'), ('PANDO', 'PANDO'), ('TARIJA', 'TARIJA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD')], max_length=255),
        ),
    ]
