# Generated by Django 5.1.2 on 2025-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0035_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('LA PAZ', 'LA PAZ'), ('TARIJA', 'TARIJA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('ORURO', 'ORURO'), ('BENI', 'BENI'), ('PANDO', 'PANDO'), ('POTOSI', 'POTOSI'), ('CHUQUISACA', 'CHUQUISACA'), ('COCHABAMBA', 'COCHABAMBA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=255),
        ),
    ]
