# Generated by Django 5.1.2 on 2025-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0036_alter_municipios_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento',
            field=models.CharField(choices=[('CHUQUISACA', 'CHUQUISACA'), ('BENI', 'BENI'), ('COCHABAMBA', 'COCHABAMBA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('ORURO', 'ORURO'), ('LA PAZ', 'LA PAZ'), ('POTOSI', 'POTOSI'), ('TARIJA', 'TARIJA'), ('PANDO', 'PANDO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='entidad_territorial',
            field=models.CharField(choices=[('GOBIERNO AUTÓNOMO REGIONAL', 'GOBIERNOS AUTÓNOMOS REGIONAL'), ('GOBIERNO AUTÓNOMO DEPARTAMENTAL', 'GOBIERNOS AUTÓNOMOS DEPARTAMENTALES'), ('GOBIERNO AUTÓNOMO MUNICIPAL', 'GOBIERNOS AUTÓNOMOS MUNICIPALES'), ('GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO', 'GOBIERNO AUTÓNOMO INDIGENA ORIGINARIO CAMPESINO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('SOLICITUD', 'SOLICITUD'), ('APROBADO', 'APROBADO'), ('NINGUNO', 'NINGUNO')], max_length=255),
        ),
    ]
