# Generated by Django 5.1.2 on 2025-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocatoria',
            old_name='extra',
            new_name='descripcion',
        ),
    ]
