# Generated by Django 5.1.2 on 2024-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_municipio',
            field=models.BooleanField(default=False, verbose_name='Estado municipio'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_revisor',
            field=models.BooleanField(default=False, verbose_name='Estado municipio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Estado municipio'),
        ),
    ]
