# Generated by Django 5.1.2 on 2024-10-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_revisor_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablep',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.persona'),
        ),
    ]
