# Generated by Django 5.1.2 on 2024-10-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_responsablep_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadomae',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.persona'),
        ),
        migrations.AlterField(
            model_name='responsablep',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.persona'),
        ),
    ]
