# Generated by Django 5.1.2 on 2025-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edtp',
            name='estado',
            field=models.CharField(choices=[('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EN EJECUCION', 'EN EJECUCION'), ('DESESTIMADO', 'DESESTIMADO'), ('FINALIZADO', 'FINALIZADO')], default='SIN REVISAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EN EJECUCION', 'EN EJECUCION'), ('DESESTIMADO', 'DESESTIMADO'), ('FINALIZADO', 'FINALIZADO')], default='SIN REVISAR', max_length=50),
        ),
    ]
