# Generated by Django 5.1.2 on 2025-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_edtp_estado_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edtp',
            name='estado',
            field=models.CharField(choices=[('SIN REVISAR', 'SIN REVISAR'), ('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EN EJECUCION', 'EN EJECUCION'), ('DESESTIMADO', 'DESESTIMADO'), ('FINALIZADO', 'FINALIZADO')], default='SIN REVISAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('SIN REVISAR', 'SIN REVISAR'), ('CON OBSERVACION', 'CON OBSERVACION'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('EN EJECUCION', 'EN EJECUCION'), ('DESESTIMADO', 'DESESTIMADO'), ('FINALIZADO', 'FINALIZADO')], default='SIN REVISAR', max_length=50),
        ),
    ]
