# Generated by Django 5.1.2 on 2024-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fechaLanzamiento', models.DateField()),
                ('horaLanzamiento', models.TimeField()),
                ('fechaCierre', models.DateField()),
                ('horaCierre', models.TimeField()),
                ('montoElabEDTP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montoEjecEDTP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'Convocatoria',
                'managed': True,
            },
        ),
    ]
