# Generated by Django 5.1.2 on 2025-02-09 02:09

import convocatoria.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=255, null=True)),
                ('fechaLanzamiento', models.DateField()),
                ('horaLanzamiento', models.TimeField()),
                ('fechaCierre', models.DateField()),
                ('horaCierre', models.TimeField()),
                ('montoElabEDTP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montoEjecEDTP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('tamanoDoc', models.IntegerField(choices=[(2, 2), (5, 5), (8, 8), (10, 10), (15, 15)], default=2)),
                ('elabEdtp', models.BooleanField(default=False)),
                ('EjecEdtp', models.BooleanField(default=False)),
                ('documento', models.FileField(upload_to=convocatoria.upload.convocatoria_doc)),
                ('guia', models.FileField(upload_to=convocatoria.upload.convocatoria_doc)),
                ('guiaVideo', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=convocatoria.upload.convocatoria_doc)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'Convocatoria',
                'managed': True,
            },
        ),
    ]
