# Generated by Django 5.1.2 on 2024-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
