# Generated by Django 5.1.2 on 2025-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_alter_convocatoria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='tamañoDoc',
            field=models.IntegerField(choices=[(2, 2), (5, 5), (8, 8), (10, 10), (15, 15)], default=2),
        ),
    ]
