# Generated by Django 5.1.2 on 2025-01-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0003_convocatoria_tamañodoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocatoria',
            old_name='tamañoDoc',
            new_name='tamanoDoc',
        ),
    ]
