# Generated by Django 5.1.2 on 2025-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0004_rename_tamañodoc_convocatoria_tamanodoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='extra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
