# Generated by Django 5.1.2 on 2025-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0005_convocatoria_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='EjecEdtp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='elabEdtp',
            field=models.BooleanField(default=False),
        ),
    ]
