# Generated by Django 5.1.2 on 2025-01-30 15:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0006_convocatoria_ejecedtp_convocatoria_elabedtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='extra',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
