# Generated by Django 5.1.2 on 2025-01-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0007_alter_convocatoria_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='extra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
