# Generated by Django 5.1.2 on 2025-01-31 00:59

import convocatoria.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0008_alter_convocatoria_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to=convocatoria.upload.convocatoria_doc),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=convocatoria.upload.convocatoria_doc),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='guia',
            field=models.FileField(blank=True, null=True, upload_to=convocatoria.upload.convocatoria_doc),
        ),
    ]
