# Generated by Django 5.1.2 on 2025-01-31 01:11

import convocatoria.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0009_convocatoria_banner_convocatoria_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=convocatoria.upload.convocatoria_doc),
        ),
    ]
